{
 "title": "SRE Pleno – Application Health Overview",
 "time": { "from": "2026-01-07T22:49:21.558Z", "to": "2026-01-07T23:12:22.542Z" },
 "panels": [
  { "title": "HTTP Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m]))",
     "legendFormat": "req/s"
    }
   ]
  },
  {
   "title": "Request Latency p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) * 1000",
     "legendFormat": "Latency"
    },
    { "expr": "200", "legendFormat": "Warning" },
    { "expr": "500", "legendFormat": "Critical" }
   ]
  },
  {
   "title": "HTTP 4xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"4..\"}[5m]))",
     "legendFormat": "4xx errors/s"
    },
    {
     "expr": "sum(rate(http_requests_total[5m]))*0.05",
     "legendFormat": "Warning"
    },
    {
     "expr": "sum(rate(http_requests_total[5m]))*0.1",
     "legendFormat": "Critical"
    }
   ]
  },
  {
   "title": "HTTP 5xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[1m]))",
     "legendFormat": "5xx errors/s"
    },
    { "expr": "1", "legendFormat": "Warning" },
    {
     "expr": "sum(rate(http_requests_total[5m]))*0.05",
     "legendFormat": "Critical"
    }
   ]
  },
  { "title": "APP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"sre-test\", pod=~\"sre-app.*\"}[5m]))",
     "legendFormat": "{{ pod }}"
    },
    { "expr": "0.7", "legendFormat": "Warning" },
    { "expr": "0.85", "legendFormat": "Critical" }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (pod) (container_memory_working_set_bytes{pod=~\"sre-app.*\", namespace=\"sre-test\"}) / \r\n sum by (pod) (kube_pod_container_resource_limits{resource=\"memory\", pod=~\"sre-app.*\", namespace=\"sre-test\"})) * 100",
     "legendFormat": "__auto"
    },
    { "expr": "75", "legendFormat": "Warning" },
    { "expr": "90", "legendFormat": "Critical" }
   ]
  },
  {
   "title": "Restart",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"sre-test\", pod=~\"sre-app.*\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Node.js Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds * 1000",
     "legendFormat": "{{ pod }}"
    },
    { "expr": "50", "legendFormat": "Warning" },
    { "expr": "100", "legendFormat": "Critical" }
   ]
  }
 ]
}